#cloud-config

users:
  - name: runner
    shell: /bin/bash

packages:
  - git
  - nginx
  - golang-go

apt:
  sources:
    golang-backports:
      source: "ppa:longsleep/golang-backports"

write_files:
  - path: /etc/systemd/system/apparea.service
    owner: root:root
    content: |
      [Unit]
      Description=AppArea
      After=network.target

      [Service]
      Type=simple
      User=runner
      Group=runner
      ExecStart=/usr/local/bin/apparea serve --bind-ssh 0.0.0.0:21 --bind-http localhost:8000
      Restart=always
      RestartSec=30

      [Install]
      WantedBy=multi-user.target
  - content: |
      server {
        server_name apparea.dev;
        client_max_body_size 2m;

        listen 80;
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        ssl_certificate_key /etc/certs/apparea.pem;
        ssl_certificate /etc/certs/apparea.crt;
        ssl_session_timeout 1d;
        ssl_session_cache shared:MozSSL:10m;
        ssl_session_tickets off;
        
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers off;

        location / {
          proxy_pass http://localhost:8000;
          proxy_set_header Host $host;
        }
      }
    owner: "root:root"
    path: "/etc/nginx/sites-available/default"
  - content: "${base64encode(tls_cert)}"
    encoding: b64
    owner: "root:root"
    path: "/etc/certs/apparea.crt"
  - content: "${base64encode(tls_key)}"
    encoding: b64
    owner: "root:root"
    path: "/etc/certs/apparea.pem"
  - content: |
      auto eth0:1
      iface eth0:1 inet static
          address ${ip_address}
          netmask 32
    owner: "root:root"
    path: "/etc/network/interfaces.d/60-my-floating-ip.cfg"

runcmd:
  - "service networking restart"
  - "HOME=/home/runner GOPATH=/home/runner/go go get github.com/jedevc/apparea"
  - "HOME=/home/runner GOPATH=/home/runner/go go install github.com/jedevc/apparea"
  - "cp /home/runner/go/bin/apparea /usr/local/bin"
  - "setcap CAP_NET_BIND_SERVICE+ep /usr/local/bin/apparea"
  - "sudo -u runner -- apparea setup"
  - "systemctl start apparea.service"
  - "systemctl enable apparea.service"
