#cloud-config

users:
  - name: runner
    shell: /bin/bash

packages:
  - git
  - nginx
  - golang-go
  - python3
  - python3-pip
  - software-properties-common
  - certbot

apt:
  sources:
    golang-backports:
      source: "ppa:longsleep/golang-backports"
    certbot:
      source: "ppa:certbot/certbot"

write_files:
  - owner: "root:root"
    path: /etc/network/interfaces.d/60-my-floating-ip.cfg
    content: |
      auto eth0:1
      iface eth0:1 inet static
          address ${ip_address}
          netmask 32
  - path: /etc/systemd/system/apparea.service
    owner: "root:root"
    content: |
      [Unit]
      Description=AppArea
      After=network.target

      [Service]
      Type=simple
      User=runner
      Group=runner
      ExecStart=/usr/local/bin/apparea serve --bind-ssh 0.0.0.0:21 --bind-http localhost:8000
      Restart=always
      RestartSec=30

      [Install]
      WantedBy=multi-user.target
  - path: /root/gandi.ini
    owner: "root:root"
    permissions: "0600"
    content: |
      certbot_plugin_gandi:dns_api_key=${gandi_api_key}
  - path: /etc/nginx/sites-available/default
    owner: "root:root"
    content: |
      server {
        server_name apparea.dev;
        client_max_body_size 2m;

        listen 80;
        listen [::]:80;
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        ssl_certificate_key /etc/letsencrypt/live/apparea.dev/privkey.pem;
        ssl_certificate /etc/letsencrypt/live/apparea.dev/cert.pem;
        ssl_session_timeout 1d;
        ssl_session_cache shared:MozSSL:10m;
        ssl_session_tickets off;
        
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers off;

        location / {
          proxy_pass http://localhost:8000;
          proxy_set_header Host $host;
        }
      }
  - path: /root/apparea-update.sh
    permissions: "0755"
    content: |
      #!/bin/bash

      set -e

      export HOME=/home/runner
      export GOPATH=/home/runner/go

      go get -u github.com/jedevc/apparea
      go install github.com/jedevc/apparea
      cp /home/runner/go/bin/apparea /usr/local/bin
      setcap CAP_NET_BIND_SERVICE+ep /usr/local/bin/apparea

runcmd:
  - "service networking restart"
  - "pip3 install certbot-plugin-gandi"
  - "certbot certonly -n \
        --email jedevc@gmail.com --agree-tos
        -a certbot-plugin-gandi:dns \
        --certbot-plugin-gandi:dns-credentials /root/gandi.ini \
        -d 'apparea.dev' -d '*.apparea.dev' \
        --server https://acme-staging-v02.api.letsencrypt.org/directory"
  - "systemctl restart nginx.service"
  - "/root/apparea-update.sh"
  - "sudo -u runner -- apparea setup"
  - "systemctl enable apparea.service --now"
