#cloud-config

users:
  - name: runner
    shell: /bin/bash

packages:
  - git
  - nginx
  - golang-go
  - python3
  - python3-pip
  - software-properties-common
  - certbot

apt:
  sources:
    golang-backports:
      source: "ppa:longsleep/golang-backports"
    certbot:
      source: "ppa:certbot/certbot"

write_files:
  - owner: "root:root"
    path: /etc/network/interfaces.d/60-my-floating-ip.cfg
    content: |
      auto eth0:1
      iface eth0:1 inet static
          address ${ip_address}
          netmask 32
  - path: /etc/systemd/system/apparea.service
    owner: "root:root"
    content: |
      [Unit]
      Description=AppArea
      After=network.target

      [Service]
      Type=simple
      User=runner
      Group=runner
      ExecStart=/usr/local/bin/apparea serve --bind-ssh 0.0.0.0:21 --bind-http localhost:8000
      Restart=always
      RestartSec=30

      [Install]
      WantedBy=multi-user.target
  - path: /root/gandi.ini
    owner: "root:root"
    permissions: "0600"
    content: |
      certbot_plugin_gandi:dns_api_key=${gandi_api_key}
  - path: /etc/nginx/sites-available/default
    owner: "root:root"
    content: |
      server {
        server_name apparea.dev;
        client_max_body_size 2m;

        listen 80;
        listen [::]:80;
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        ssl_certificate_key /etc/letsencrypt/live/apparea.dev/privkey.pem;
        ssl_certificate /etc/letsencrypt/live/apparea.dev/fullchain.pem;
        ssl_session_timeout 1d;
        ssl_session_cache shared:MozSSL:10m;
        ssl_session_tickets off;
        
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers off;

        location / {
          root /home/runner/apparea-site/public/;
        }
      }

      server {
        server_name *.apparea.dev;
        client_max_body_size 2m;

        listen 80;
        listen [::]:80;
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        ssl_certificate_key /etc/letsencrypt/live/apparea.dev/privkey.pem;
        ssl_certificate /etc/letsencrypt/live/apparea.dev/fullchain.pem;
        ssl_session_timeout 1d;
        ssl_session_cache shared:MozSSL:10m;
        ssl_session_tickets off;
        
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers off;

        location / {
          proxy_pass http://localhost:8000;
          proxy_set_header Host $host;
        }
      }
  - path: /root/update/apparea.sh
    permissions: "0755"
    content: |
      #!/bin/bash

      set -e

      export HOME=/home/runner
      export GOPATH=/home/runner/go

      STATUS=$(systemctl is-active apparea)

      go get -u github.com/jedevc/apparea
      go install github.com/jedevc/apparea

      if [[ $STATUS -eq active ]]; then
        systemctl stop apparea | true
      fi
      cp /home/runner/go/bin/apparea /usr/local/bin
      setcap CAP_NET_BIND_SERVICE+ep /usr/local/bin/apparea
      if [[ $STATUS -eq active ]]; then
        systemctl start apparea | true
      fi
  - path: /root/update/hugo.sh
    permissions: "0755"
    content: |
      #!/bin/bash

      set -e

      curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest \
        | grep browser_download_url \
        | grep Linux-64bit.deb \
        | grep extended \
        | cut -d '"' -f 4 \
        | wget -i - && \
        dpkg -i *.deb && \
        rm *.deb
  - path: /root/update/site.sh
    permissions: "0755"
    content: |
      #!/bin/bash

      set -e

      export HOME=/home/runner
      cd $HOME

      rm -rf apparea-site
      git clone https://github.com/jedevc/apparea-site.git --recurse-submodules
      cd apparea-site

      hugo

runcmd:
  - "timedatectl set-timezone UTC"
  - "service networking restart"

  - "pip3 install certbot-plugin-gandi"
  - "certbot certonly -n \
        --email jedevc@gmail.com --agree-tos
        -a certbot-plugin-gandi:dns \
        --certbot-plugin-gandi:dns-credentials /root/gandi.ini \
        -d 'apparea.dev' -d '*.apparea.dev'"
  - "systemctl restart nginx.service"

  - "/root/update/hugo.sh"
  - "/root/update/site.sh"

  - "/root/update/apparea.sh"
  - "sudo -u runner -- apparea setup"
  - "systemctl enable apparea.service --now"
